### ISSUE TITLE
Unable to build the image

### ISSUE THREAD

**Issue by sirspock** [mintproject/MINT-Transformation#65]
```bash
$ docker build -t mint_dt .
...

Preparing transaction: ...working... done
Verifying transaction: ...working... done
Executing transaction: ...working... done


==> WARNING: A newer version of conda exists. <==
  current version: 4.7.12
  latest version: 4.8.3

Please update conda by running

    $ conda update -n base -c defaults conda


Pip subprocess error:
ERROR: Invalid requirement: 'pyocclient=' (from line 20 of /tmp/condaenv.gcilt0at.requirements.txt)
Hint: = is not a valid operator. Did you mean == ?


CondaEnvException: Pip failed
```

Reason: 
Missing package version
https://github.com/mintproject/MINT-Transformation/blob/master/environment.yml#L34

**Comment by sirspock** [comment]
@minhptx ping

**Comment by dgarijo** [comment]
copying @summer7xinting  too

**Comment by summer7xinting** [comment]
I'm rebuilding the image to debug this

**Comment by summer7xinting** [comment]
![image](https://user-images.githubusercontent.com/18204249/81221567-dedbc580-8f97-11ea-8864-5f854967120b.png)
My rebuild is successful. I'm using Mac Catalina. 
Are you guys working with master?

**Comment by summer7xinting** [comment]
I believe the pip specification of pyocclient is valid. Can you guys update the conda and try rebuilding the docker image inside conda env `mintdt`?

**Comment by minhptx** [comment]
@dgarijo @sirspock I fixed the bug last week but forgot to close the issue. Sorry all.
